### ISSUE TITLE
As a customer, I want to borrow a book so that I can go to the library and take that book.

### ISSUE THREAD

**Issue by AsemLab** [amer-sabah/bookshelf#1]

**Comment by AsemLab** [comment]
**Use case name:** Borrow a book
**Brief description:** Customer browses available books and choose a book for borrow
**Actor:** Customer
**Preconditions:** None
**Main flow:**
1.	Customer searches and chooses the library from libraries window.
2.	System opens the library window.
3.	Customer searches and selects the book from the available books.	 
4.	Customer clicks on borrow button.
5.	System adds the user details to the borrow list.
6.	Library owner accepts customer request.
7.	System adds the user details in the history of the library.
8.	System adds the transaction to user's log.

**Postcondition:** The customer can go to the library and borrow the desired book.
**Alternatives:**
-  In step 3, there is no available book so the system shows a message when  the book is will be available and stop the other steps.
-  In step 6, the owner reject the request then the system shows a message to alert the customer and end execution.

**Comment by AsemLab** [comment]
### The required tables:

1. **Customers** (id, email, borrow_history)
2. **Library owners** ( id. library)
3. **libraries** (id, books)
4. **books** (id)

**Comment by Amalqazaq** [comment]
@maiqamaj please test

**Comment by maiqamaj** [comment]
1- Owner should watch borrow and return date to manage number of books that borrowed 
2- Customer should not enter his information on each borrow process again because the system contain all his information in the first sign up in system 
3- When library Owner reject the borrow request the system send to Customer reject notification Not delete borrow request details (should coustmer watch statuse for his request if reject or accept )
and not removing the customer from system which is wrong

please check your work again @Amalqazaq

**Comment by Amalqazaq** [comment]
@maiqamaj ,  I fix the bugs , please test.
